remote_theme: pages-themes/architect@v0.2.0
title: Remote Volume
description: Adjust the PC volume from your mobile

show_downloads: True

github:
  zip_url: https://github.com/rybafish/remoteVolume/releases/download/v0.1beta/RemoteVolume_01beta.7z
  another_url: False
